.travis.yml
This is a relatively simple .travis.yml file. We can extend it as we go. It is valid according to https://lint.travis-ci.org/ . Currently, it will fail due to testifycompat being required for the tests to run. However, we can simply disable automatic builds on the travis website until we sort out that issue.
=> Add initial .travis.yml file

MANIFEST.in, setup.py
yelp_clog apparantly is not compatible with the latest version of
thriftpy. So we pin to 0.1.15. Also add a MANIFESTS.in to ensure we are
including all necessary files in our module.
=> Add MANIFESTS.in and pin thriftpy version

LICENSE, clog/__init__.py, clog/config.py, clog/global_state.py, clog/handlers.py, clog/loggers.py, clog/readers.py, clog/scribe_net.py, clog/utils.py, docs/source/conf.py, setup.py, testing/__init__.py, testing/sandbox.py, testing/util.py, tests/__init__.py, tests/config_test.py, tests/test_clog.py, tests/test_handlers.py, tests/test_readers.py, tests/test_scribe_timeout.py, tests/test_scribelogger_line_size.py, tests/test_scribelogger_report_status.py, tests/test_tailer.py
Add license headers to all of the scripts in yelp_clog. This is done so that if a user decides to use a single file from yelp_clog (rather than cloning the entire repository), it is instantly clear what license the file is released under; they do not need to hunt down the original repository to check.
=> Add license headers to files

clog/utils.py, testing/sandbox.py, tests/test_clog.py
- Renamed 2 tests so they actually run under pytest (lol)
- Fixed the port race under test
- Fix `scribify` function
=> Fix scribify on py3

clog/handlers.py, tests/test_handlers.py
Example traceback when I initialized ScribeHandler without a retry_interval set:
```
--- Logging error ---
Traceback (most recent call last):
File "/nail/home/kkelly/y/scarab_scribe_extension/venv/lib/python3.4/site-packages/clog/handlers.py", line 83, in emit
self.logger.log_line(self.stream, msg)
File "/nail/home/kkelly/y/scarab_scribe_extension/venv/lib/python3.4/site-packages/clog/loggers.py", line 209, in log_line
self._log_line_no_size_limit(stream, line)
File "/nail/home/kkelly/y/scarab_scribe_extension/venv/lib/python3.4/site-packages/clog/loggers.py", line 177, in _log_line_no_size_limit
self._maybe_reconnect()
File "/nail/home/kkelly/y/scarab_scribe_extension/venv/lib/python3.4/site-packages/clog/loggers.py", line 160, in _maybe_reconnect
if (now - self.last_connect_time) > …
```
=> Fix bug where ScribeHandler errors and fails to log if retry_interval is not set

clog/__init__.py, clog/loggers.py, clog/readers.py, clog/utils.py, setup.py, tests/test_readers.py, tests/test_tailer.py
CC @bukzor
We've identified future as a problematic library when working in a python2 space.  It does the following things which are "useful" but often cause problems for code which does not expect them (or already correctly handles python2+3):
- Introduces two new string types `newstr` and `newbytes` which act like the python3 equivalents.  Libraries (including the stdlib (especially urlparse / urllib)) will happily attempt to `str(...)` these objects.  This will end up converting `newbytes` to `"b'foo'"` which is somewhat problematic
- These types can leak out of libraries which correctly handle them into libraries which do not (and do not expect them!).
- It installs aliases to the new stdlib libraries in the default import space (making things like `import configparser` (in python2 …
=> Switch from future to six

clog/loggers.py, tests/test_clog.py
I ran into an issue where the logs directory didn't exist in a docker container. If I had immediately known which directory it was trying to write to, it would have saved me a lot of debugging time. Therefore, I decided to add the directory to the error message.
This also adds test coverage for that error case.
=> Log the directory when clog is unable to open the stream for writing.

.gitignore, clog/loggers.py, tests/test_clog.py
Before this change:
```
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/code/biz_messaging/kew_workers/email_reply_processor_worker.py", line 56, in <module>
EmailReplyProcessor().start()
File "/code/virtualenv_run/lib/python3.5/site-packages/yelp_batch/batch.py", line 559, in start
self._log_shutdown(exit_code)
File "/code/virtualenv_run/lib/python3.5/site-packages/yelp_batch/batch.py", line 602, in _log_shutdown
self.log.info(shutdown_msg)
File "/usr/lib/python3.5/logging/__init__.py", line 1279, in info
self._log(INFO, msg, args, **kwargs)
File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log …
```
=> Make sure that we can create files using the FileLogger in python3.

clog/readers.py, tests/test_tailer.py
As we described in CEP611, yelp_clog readers need to pass region or superregion to scribe tailer service so that it can tail the correct kafka cluster.
This change is backwards compatible since two new params are optional. For the old services or libs that depend on yelp_clog, they should continue to work.
make test passes locally.
=> Add region and superregion

CHANGELOG.rst, clog/__init__.py, clog/loggers.py, setup.py
A quick assertion to make sure that people are only attempting to log strings/text, and that attempting to log other other types isn't eaten by the mock.
=> Adding type checking within MockLoggers log_line function

setup.py, tox.ini
Looks like python3.6 changed the way os.path.join works:
```python
ipdb> type(clog_config.log_dir)
<class 'staticconf.proxy.ValueProxy'>
ipdb> os.path.join(clog_config.log_dir, 'hi')
'/nail/tmp/hi'
(Pdb) type(clog_config.log_dir)
<class 'staticconf.proxy.ValueProxy'>
(Pdb) os.path.join(clog_config.log_dir, 'hi')
*** TypeError: expected str, bytes or os.PathLike object, not ValueProxy
```
A bunch of os methods now only accept 'path-like objects' (https://docs.python.org/3/glossary.html#term-path-like-object) where they seemed previously fine with ValueProxies from staticconf.
Added a tox env for py36 and fixed the two failures here. I don't know if there are other more subtle problems in py36: happy to expand this PR.
=> Add support for py36

clog/__init__.py, clog/uwsgi_plugin.py, setup.py
This PR introduces a uwsgi_plugin which adds opt-in functionality for clogging from mule processes, which brief benchmarking shows a 10x speedup in the critical path. The module is tentatively loaded at import time and, if in a uwsgi environment, will configure the mule dispatcher to have references to the `clog.global_state.log_line` function. Then any worker may call `clog.uwsgi_log_line` to dispatch a logging request to a mule. 
Alternatively the user may call `clog.uwsgi_patch_global_state` to monkey-patch the global state logger to dispatch to mules - in this vein there is an associated yelp_servlib.clog_util change that will to this inside initialization based on a configuration option. 
Lastly there's a UwsgiHandler class which can be attached to any logger that will dispatch …
=> Add uwsgi_plugin module

clog/uwsgi_plugin.py, testing/sandbox.py, tests/test_uwsgi_plugin.py, tox.ini
It turns out attempting to marshal.loads data which isn't marshal
serialized can hang indefinitely. Let's not do that.
=> Add uwsgi_plugin clog message header

clog/readers.py
The list_streams method of StreamTailer currently ignores the protocol_opts.
This will ensure and protocol options are used when list_streams is called.
=> KAFKA-2979: Use protocol_opts when calling list_streams.

clog/readers.py, tests/test_readers.py
We want to fail fast instead of connecting to the wrong host.
=> KAFKA-5162: Raise exception when host mapping file missing.

clog/config.py, clog/loggers.py, clog/metrics_reporter.py, requirements.txt, setup.py, tests/test_metrics_reporter.py
Should probably figure out what our plan to deploy and configure it (right now just using a static 1/1000 sampling rate), but this should at least have the logging there.
=> MONK-146 Add MetricsReporter class that can sample latency for clog.log_line calls

clog/config.py, clog/global_state.py, clog/handlers.py, clog/zipkin_plugin.py, setup.py, testing/sandbox.py, tests/test_zipkin_plugin.py
If py_zipkin is installed and use_zipkin setting is set to True, calls to .log_line
of any logger will be instrumented with Zipkin.
service_name=yelp_clog span_name={LoggerClass}.log_line {stream}
=> Add log_line Zipkin instrumentation support

clog/config.py, clog/global_state.py, clog/loggers.py, clog/metrics_reporter.py, requirements-dev.txt, setup.py, tests/test_metrics_reporter.py, tox.ini
- Emit metrics and log to syslog when messages are discarded because Monk is unavailable
- Handle timeouts: if monk is slow, timeout after 100ms and drop messages for the next 5 seconds, then retry (configurable).
- Monk prefix configurable
- Add optional stream -> backend (monk/scribe/dual) map
=> Clog monk improvements

clog/global_state.py, clog/loggers.py
If 'monk_disable' is false but Monk is not available as a dependency,
don't throw an exception. This will make transitioning to Monk easier,
since we can set 'monk_disable' to false without having to upgrade all
the existing libraries.
=> MONK-292: don't throw exception if Monk clib is not installed

clog/readers.py, setup.py, tests/test_readers.py
Add support to /nail/srv/configs/yelp_clog.json as new configuration path, while adding fallback logic to the old path for backward compatibility.
=> Support multiple configuration files

clog/config.py, clog/readers.py, tests/test_readers.py
If no host/port is given for a StreamTailer, it used to look at the
configuration in the `scribe_tail_services` list. It would fail if
either this list is empty or the configuration cannot be found.
With this change applied, if no configuration can be found, the host
will be discovered using `find_tail_host`. The port can be discovered
thanks to a new configuration parameter (defaults to port 3535).
=> Default to find_tail_host when no host/port is given in StreamTailer

clog/loggers.py, tests/test_loggers_line_size.py
Enforce message size limit for the MonkLogger. Set limit to 5MB.
Also: add line preview and limit traceback size in `tmp_who_clog_large_line` stream.
=> Monk message size limit

CHANGELOG.rst, clog/loggers.py, tests/test_clog.py
Use the scribify function to convert user-provided stream names into scribe category names. This will ensure that MonkLogger is fully backward compatible with the ScribeLogger.
=> Add scribify to MonkLogger

clog/config.py, clog/loggers.py, clog/metrics_reporter.py, tests/test_clog.py
If the producer fails (e.g: Monk is restarting and is down for a while),
start buffering log lines in memory, up to a certain size threshold
(older messages will be dropped if the size of the buffer grows too much).
Buffering will stop after a configurable amount of time, all buffered
log lines will be flushed back into Monk (this would slow down the
.log_line call when flushing happens, but it should not be too much of a
trouble). If the producer fails again during flushing, all lines will be
added back to the buffer.
One datapoint is emitted every time buffering starts (maybe I should emit
one when flushing as well?) 
This does not handle STREAM_NOT_FOUND use case (it will start
buffering), but this will be tackled later I suppose.
=> Add memory buffering logic to MonkLogger

clog/config.py, clog/loggers.py
This will allow yelp_clog errors to be reported even from docker
containers. The syslog host can be configured using
`syslog_host_address`, we will probably want to set it to yocalhost.
The `SysLogHandler` in python2 does not support adding `ident` to messages, however the ident is just set by prefixing the message by `ident: `
L129-136 of https://www.retro11.de/ouxr/211bsd/usr/src/lib/libc/gen/syslog.c.html
https://docs.python.org/2/library/logging.handlers.html#sysloghandler
https://docs.python.org/3/library/logging.handlers.html#sysloghandler
=> Send errors to syslog using udp instead of unix socket

clog/loggers.py
Without this condition, turning on buffering would flush all the time, reporting rubish to syslog
=> Flush buffer only if buffering is in progress
